version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
